//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string MINIMAL_CRUSH = "minimal_crush";
        
        public const string AVERAGE_CRUSH = "average_crush";
        
        public const string SERIOUS_CRUSH = "serious_crush";
        
        public const string MINIMAL_CRASH_BACK = "minimal_crash_back";
        
        public const string RIGHTHIT = "righthit";
        
        public const string LEFTHIT = "lefthit";
    }
}
